export const DETAILS = {
  'Backyard': {
    type: 'Bootcamp',
    icon: 'barbell-outline',
    address: '2400 S Stoddard Rd, Meridian, ID 83642',
    addressLink: true,
    schedule: {
      Monday: null,
      Tuesday: null,
      Wednesday: '5:15am - 6:00am',
      Thursday: null,
      Friday: '5:15am - 6:00am',
      Saturday: null,
    },
  },
  'Bellagio': {
    type: 'Bootcamp',
    icon: 'barbell-outline',
    address: 'Kleiner Park Loop, Meridian, ID 83642',
    addressLink: true,
    schedule: {
      Monday: null,
      Tuesday: '5:15am - 6:00am',
      Wednesday: null,
      Thursday: '5:15am - 6:00am',
      Friday: null,
      Saturday: '6:00am - 7:00am',
    },
  },
  'Black Diamond': {
    type: 'High Intensity',
    icon: 'alert-circle-outline',
    address: 'Kleiner Park Loop, Meridian, ID 83642',
    schedule: {
      Monday: '5:00am - 6:00am',
      Tuesday: null,
      Wednesday: '5:00am - 6:00am',
      Thursday: null,
      Friday: null,
      Saturday: null,
    },
  },
  'Bleach': {
    type: 'Ruck/Sandbag',
    icon: 'barbell-outline',
    address: '801 Aurora Dr, Boise, ID 83709',
    addressLink: true,
    schedule: {
      Monday: '5:15am - 6:00am',
      Tuesday: null,
      Wednesday: '5:15am - 6:00am',
      Thursday: null,
      Friday: null,
      Saturday: '6:00am - 7:00am',
    },
  },
  'Gem': {
    type: 'Bootcamp',
    icon: 'barbell-outline',
    address: '3423 N Meridian Rd, Meridian, ID 83642',
    addressLink: true,
    schedule: {
      Monday: null,
      Tuesday: '5:15am - 6:00am',
      Wednesday: null,
      Thursday: '5:15am - 6:00am',
      Friday: null,
      Saturday: '6:00am - 7:00am',
    },
  },
  'Iron Mountain': {
    type: 'Bootcamp',
    icon: 'barbell-outline',
    address: '75 Marjorie Ave, Middleton, ID 83644',
    addressLink: true,
    schedule: {
      Monday: null,
      Tuesday: '5:30am - 6:15am',
      Wednesday: null,
      Thursday: '5:30am - 6:15am',
      Friday: null,
      Saturday: '6:00am - 7:00am',
    },
  },
  'Old Glory': {
    type: 'Bootcamp',
    icon: 'barbell-outline',
    address: '3064 W Malta Dr, Meridian, ID 83646',
    addressLink: true,
    schedule: {
      Monday: '6:00am - 6:45am',
      Tuesday: null,
      Wednesday: '6:00am - 6:45am',
      Thursday: null,
      Friday: null,
      Saturday: null,
    },
  },
  'Rebel': {
    type: 'Running',
    icon: 'footsteps-outline',
    address: '3801 E Hill Park Street, Meridian, ID 83642',
    addressLink: true,
    schedule: {
      Monday: null,
      Tuesday: '5:15am - 6:00am',
      Wednesday: null,
      Thursday: '5:15am - 6:00am',
      Friday: null,
      Saturday: null,
    },
  },
  'Rise': {
    type: 'Bootcamp',
    icon: 'barbell-outline',
    address: '4403 S Surprise Way, Boise, ID 83716',
    addressLink: true,
    schedule: {
      Monday: '5:15am - 6:00am',
      Tuesday: null,
      Wednesday: '5:15am - 6:00am',
      Thursday: null,
      Friday: null,
      Saturday: null,
    },
  },
  'Ruckership East': {
    type: 'Ruck/Hike',
    icon: 'footsteps-outline',
    address: 'Location changes every week',
    addressLink: false,
    schedule: {
      Monday: null,
      Tuesday: null,
      Wednesday: null,
      Thursday: null,
      Friday: '5:30am - 6:30am',
      Saturday: null,
    },
  },
  'Ruckership West': {
    type: 'Ruck/Hike',
    icon: 'footsteps-outline',
    address: 'Location changes every week',
    addressLink: false,
    schedule: {
      Monday: null,
      Tuesday: null,
      Wednesday: null,
      Thursday: null,
      Friday: '5:30am - 6:30am',
      Saturday: null,
    },
  },
  'The Tower': {
    type: 'Bootcamp',
    icon: 'barbell-outline',
    address: '2121 E Lake Hazel Rd, Meridian, ID 83642',
    addressLink: true,
    schedule: {
      Monday: null,
      Tuesday: null,
      Wednesday: null,
      Thursday: null,
      Friday: null,
      Saturday: '6:00am - 7:00am',
    },
  },
  'War Horse': {
    type: 'Bootcamp',
    icon: 'barbell-outline',
    address: '1304 7th St N, Nampa, ID 83687',
    addressLink: true,
    schedule: {
      Monday: '5:15am - 6:00am',
      Tuesday: null,
      Wednesday: '5:15am - 6:00am',
      Thursday: null,
      Friday: null,
      Saturday: null,
    },
  },
};